### ISSUE TITLE
E-Mail import not worked after install this plugin

### ISSUE THREAD

**Issue by Spam-Spamych** [tomolimo/mailbehaviours#5] opened 2021-03-03 09:12 UTC
This is for English only. What about others?
For example - German: From -> Von.
Or a configuration page with custom "From" and "CC" fields.
Thanks!

**Comment by Spam-Spamych** [comment] 2021-03-03 09:36
I have tried, but unfortunately:
[php-errors.log](https://github.com/tomolimo/mailbehaviours/files/6074946/php-errors.log)


```
Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594
```

**Comment by tomolimo** [comment] 2021-03-03 10:27
Hello @Spam-Spamych 
Could you give more details about GLPI configuration?
Could you also explain in details what are the steps to reproduce the issue?
Thank you
Regards,
Tomolimo

**Comment by Spam-Spamych** [comment] 2021-03-03 13:54
Hi Tomolimo!

I have GLPi 9.5.3 with German language. PHP 7.4.11. 

What have I done:
- Login in GLPi as "glpi".
- Plugin installed and activated.
- Corrected an email (in German) as described by you - before `From` I added `##`. (I just had to replace the German word `Von` with the English word `From`.)
- In GLPi "**Setup / Receivers**" click on Receiver and then on `Actions` and `Get email ticket now` 

In "php-errors.log" ist the same error. 
But I no longer have this error. 
`Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed\htmLawed.php on line 594` 
Only empty window and no emails were imported:

Regards,
S.

**Comment by tomolimo** [comment] 2021-03-03 15:06
Hello @Spam-Spamych 

Could you look in the browser console log if they are any error logged? To get into the browser console press F12 (or CTRL+Shift+i) and redo the steps to reproduce this issue.

Thank you
Regards,
Tomolimo

**Comment by Spam-Spamych** [comment] 2021-03-03 18:26
Hello Tomolimo.

Chrome:
![Chrome](https://user-images.githubusercontent.com/72871566/109852979-aeb39080-7c55-11eb-8185-81be792b4b55.jpg)

Firefox:
![Firefox](https://user-images.githubusercontent.com/72871566/109852983-af4c2700-7c55-11eb-906f-c7e8888e5f86.jpg)

Regerds.
S.

**Comment by Spam-Spamych** [comment] 2021-03-03 18:49
Email text:

`##From: Maxxxx, Loxxxxx <xxxxxx@xxxxxxxxx.com>`

Regards,
S.

**Comment by Spam-Spamych** [comment] 2021-03-03 19:11
[Debugger picture. Click here](https://user-images.githubusercontent.com/72871566/109858539-3e5c3d80-7c5c-11eb-91df-867d29467a9e.jpg)

[Debugger picture with $message variable. Click here](https://user-images.githubusercontent.com/72871566/109862200-74032580-7c60-11eb-8b18-6d193c877725.jpg)

**Comment by tomolimo** [comment] 2021-03-04 16:15
Hello @Spam-Spamych 

I understand the root cause of the issue, and I'm sorry because, in fact there is a bug in GLPI 9.5.3 that is fixed in GLPI 9.5.4
In the release of the mailanalyzer plugin I posted a fix for this bug, and for the mailbehaviours plugin, you must use the same fix.
It's here: [GLPI 9.5.3 mailcollector.class.php bug fix](https://github.com/tomolimo/mailanalyzer/releases/tag/2.0.0)

Thank you,
Regards,
Tomolimo

**Comment by Spam-Spamych** [comment] 2021-03-05 13:14
Hello Tomolimo.
It's worked! Many thanks!

But what about [post 1](https://github.com/tomolimo/mailbehaviours/issues/5#issue-820910069) 

Regards,
S.

**Comment by tomolimo** [comment] 2021-03-05 13:19
Hello @Spam-Spamych 
That's a good idea, we may have a list of keywords
But please do not mix issues that are requests with issues that are incidents!
So please create a new issue for that request, and change the title of the current one to reflect the real issue meaning.
Thank you,
Regards,
Tomolimo

**Closed as completed** 2021-03-05 13:41 UTC
